In [ ]:
!nvidia-smi

Mon Jan  8 20:16:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import torch
from torch import nn

In [ ]:
weight = 0.7
bias = 0.3
x = torch.arange(0, 1, 0.02).unsqueeze(dim = 1)
y = weight * x + bias

In [ ]:
# prompt: print x and y

print(x.shape)
print(y)


torch.Size([50, 1])
tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260],
        [0.4400],
        [0.4540],
        [0.4680],
        [0.4820],
        [0.4960],
        [0.5100],
        [0.5240],
        [0.5380],
        [0.5520],
        [0.5660],
        [0.5800],
        [0.5940],
        [0.6080],
        [0.6220],
        [0.6360],
        [0.6500],
        [0.6640],
        [0.6780],
        [0.6920],
        [0.7060],
        [0.7200],
        [0.7340],
        [0.7480],
        [0.7620],
        [0.7760],
        [0.7900],
        [0.8040],
        [0.8180],
        [0.8320],
        [0.8460],
        [0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])


In [ ]:
if torch.cuda.is_available():
  print("PyTorch is running on GPU.")
else:
  print("PyTorch is running on CPU.")

PyTorch is running on GPU.


In [ ]:
x = x.numpy()
y = y.numpy()

In [ ]:
x = x.reshape(50, 2)
y = y.reshape(50, 2)

In [ ]:
l = []
for i in range(50):
  l.append([x[i], y[i]])

k = np.array(l).reshape(50,2)
k.shape

(50, 2)

In [ ]:
k

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
x_train = torch.tensor(x_train)
x_test = torch.tensor(x_test)
y_train = torch.tensor(y_train)
y_test = torch.tensor(y_test)

torch.Size([1, 1])

In [ ]:
class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1))
    self.bias = nn.Parameter(torch.randn(1))
    print(self.weights)
    print(self.bias)
  def forward(self, tensor: torch.tensor) -> torch.tensor:
    return self.weights * tensor + self.bias

In [ ]:
lr = LinearRegression()
lr.parameters()

Parameter containing:
tensor([1.2627], requires_grad=True)
Parameter containing:
tensor([0.5196], requires_grad=True)


<generator object Module.parameters at 0x7f94ad3b2260>

In [ ]:
biloss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params = lr.parameters(), lr = 0.00001)

In [ ]:
epochs = 200

for i in range(epochs):
  lr.train()
  y_pred = lr(x_train)
  loss = loss_fn(y_pred, y_train)
  print(loss)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()


tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)
tensor(0.0001, grad_fn=<MeanBackward0>)


In [ ]:
k = torch.tensor([[1]])

In [ ]:
k.shape

torch.Size([2])

In [ ]:
list(lr.parameters())

[Parameter containing:
 tensor([0.7001], requires_grad=True),
 Parameter containing:
 tensor([0.2999], requires_grad=True)]

In [ ]:
import torch

k = torch.tensor([1,2,3])
k = k.unsqueeze(dim = 1)
r = torch.rand(2,3)

In [ ]:
torch.rand(1,1)

tensor([[0.3357]])

In [ ]:
plot(y = dbinom(1:100,n = 100, prob = 0.01))